[package]
name = "madsim"
version = "0.1.0"
edition = "2018"
authors = ["Runji Wang <wangrunji0408@163.com>"]
description = "Deterministic Simulator for distributed systems."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
rpc = ["serde", "flexbuffers"]
macros = ["madsim-macros"]

[dependencies]
madsim-macros = { path = "../madsim-macros", optional = true }
log = "0.4"
rand = { version = "0.8", features = ["small_rng"] }
async-task = "4.0"
futures = "0.3"
naive-timer = "0.2"
serde = { version = "1.0", features = ["derive"], optional = true }
flexbuffers = { version = "2.0", optional = true }

[dev-dependencies]
env_logger = "0.8"
