[package]
name = "madsim"
version = "0.1.1"
edition = "2018"
authors = ["Runji Wang <wangrunji0408@163.com>"]
description = "Deterministic Simulator for distributed systems."
readme = "../README.md"
homepage = "https://github.com/madsys-dev/madsim"
repository = "https://github.com/madsys-dev/madsim"
license = "Apache-2.0"
keywords = ["distributed-systems", "async", "deterministic", "simulation"]
categories = ["asynchronous", "simulation"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["macros"]
sim = ["madsim-sim"]
std = ["madsim-std"]
ucx = ["std", "madsim-std/ucx"]
macros = ["madsim-macros"]

[dependencies]
madsim-macros = { version = "0.1.1", path = "../madsim-macros", optional = true }
madsim-sim = { path = "../madsim-sim", features = ["rpc", "logger"], optional = true }
madsim-std = { path = "../madsim-std", features = ["rpc", "logger"], optional = true }

[package.metadata.docs.rs]
all-features = true
