[package]
name = "madsim-tonic"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
# dev tip: uncomment this to enable analyzer
# default = ["sim"]
sim = []

[dependencies]
futures-core = "0.3"
tonic = "0.7"
tower-service = "0.3"
