[package]
name = "madsim-tonic-build"
version = "0.1.0"
edition = "2021"
authors = ["Lucio Franco <luciofranco14@gmail.com>", "Runji Wang <wangrunji0408@163.com>"]
description = "Codegen module of `madsim-tonic` gRPC implementation."
homepage = "https://github.com/madsys-dev/madsim"
repository = "https://github.com/madsys-dev/madsim"
categories = ["network-programming", "asynchronous"]
keywords = ["rpc", "grpc", "async", "codegen", "protobuf"]
readme = "README.md"
license = "MIT"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proc-macro2 = "1"
prost-build = "0.10"
quote = "1"
syn = "1"
