name: CI

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt, clippy
      - name: Check code format
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      - name: Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: Test std
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release --no-fail-fast -p madsim
      - name: Test sim
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release --no-fail-fast -p madsim --features=sim
      - name: Test tonic
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release --no-fail-fast -p tonic-example --features=tonic/sim

  bench:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: Bench
        uses: actions-rs/cargo@v1
        with:
          command: bench
          args: -p madsim

  doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          override: true
          toolchain: nightly
      - name: Doc
        uses: actions-rs/cargo@v1
        env:
          RUSTDOCFLAGS: "--cfg docsrs"
        with:
          command: doc
          args: --no-deps --features=sim
